### ISSUE TITLE
Collectd attributes cause NoMethodError

### ISSUE THREAD

**Issue by andyregan** [tas50/chef-graphite_powershell_functions#1]
Thank you so much for contributing this cookbook! 

I've encountered an issue with `node['collectd']` inside `attributes/default.rb`. I'm including graphite_powershell_functions from another cookbook and even though I am overriding CarbonServer, CarbonServerPort and MetricPath I'm getting a NoMethodError during compile time. Since graphite_powershell_functions doesn't depend on collectd, would you consider removing `node['collectd']` from the default attributes?

```
c:/chef/cache/cookbooks/graphite_powershell_functions/attributes/default.rb:18:in `from_file'
NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by docwhat** [comment]
@tas50 -- Pull request submitted!
